### ISSUE TITLE
Am I supposed to edit the global variables?

### ISSUE THREAD

**Issue by Saltystew** [Chronial/snapraid-runner#10]
They just say none.

**Comment by Chronial** [comment]
Which file are you talking about?

**Comment by Saltystew** [comment]
The snapraid-runner.py, I just happen to look in it out of curiosity and noticed that the global variables section

![shot_170722_140016](https://user-images.githubusercontent.com/20447447/28493499-243b7db2-6ee6-11e7-90b6-09c0748c026a.png)

says none next to those two and I was wondering if I needed to edit those at all?

**Comment by Chronial** [comment]
As you discovered, you don't need to touch the `.py` file at all.

I'm always happy if people find my software useful :).
