### ISSUE TITLE
Add Optional Prerun and Postrun Commands?

### ISSUE THREAD

**Issue by DivinityCycle** [Chronial/snapraid-runner#14]
This is along similar lines to adding smartmon support, just with less output handling. It would be helpful to add an option to allow for arbitrary commands to be run before and/or after snapraid-runner. For example, I need to stop an instance of Plex Media Server before running a snapraid sync, and then start Plex Media Server again afterwards. This is as dumb as running a "docker stop plex" before running the snapraid processes and a "docker start plex" after.

Without built-in support for this, I need to wrap my snapraid-runner.py inside of a snapraid-runner-runner.sh, which isn't terribly elegant but works.

The main issue I can see is how to handle the output from these commands. I'm honestly not too sure what the best way to go on that would be, it's been a while since I messed around with Python subprocess handling.

**Comment by Chronial** [comment]
I don't think that should be part of snapraid-runner and feels a lot like feature-creep. While I understand that the wrapper script feels inelegant, I still think it's a perfectly adequate solution.

That kind of feature would need some complexity to handle commands to run after failure vs commands to run after success etc. I think a shell scripting language is better equipped to handle these kinds of things.
