### ISSUE TITLE
Started failing to send email via Gmail - 'Google blocking less secure app'

### ISSUE THREAD

**Issue by jtaylor54** [Chronial/snapraid-runner#16]
Been running well for a long time - tx. I had to recently change my email password and now gmail is being blocked. The error from Gmail is... "Google will continue to block sign-in attempts from the app you're using because it has known security problems or is out of date. You can continue to use this app by allowing access to less secure apps, but this may leave your account vulnerable." I am using SSL and port 465 and don't understand why it was working fine before.

**Comment by Chronial** [comment]
Probably duplicate of #6
