### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by reed-jones** [Chronial/snapraid-runner#21]
On my fork [reed-jones/snapraid-runner](https://github.com/reed-jones/snapraid-runner) I have modified the script to add python3 support. I haven't tested the email functions yet (and I haven't changed them), but everything python2 should still work the exact same. I would be happy to PR the changes back if @Chronial  is interested.

**Comment by Chronial** [comment]
Thx, I tested the email function and it seems to work. I cherry-picked your changes :+1: .

**Comment by reed-jones** [comment]
Awesome, glad I could help!
