### ISSUE TITLE
Auto fix errors after scrub

### ISSUE THREAD

**Issue by XDGFX** [Chronial/snapraid-runner#28]
Would it make sense to auto run `sudo snapraid -e fix` after a scrub detects an error? It could be implemented easily, I just wondered if there's reasoning against it being automatic? I seem to get an error almost every other sync, so would be nice if it automatically corrected them.

**Comment by Chronial** [comment]
I am strongly opposed to doing any kind of automatic fix. If a scrub detects an error, something went wrong and needs investigating.
How do you get an error on almost every sync?

**Comment by XDGFX** [comment]
This is the typical error I get

```
25782', diff bits 65/128
2020-03-05 06:40:24,240 [OUTERR] Data error in file
'/media/mfs-rainbow-lorikeet/Projects/Video/In Work/Archive/Ski Trip MMXV
Footage/Hero 3+/Day 5/GOPR1105.MP4' at position '4275', diff bits 62/128
2020-03-05 09:33:14,660 [OUTERR] DANGER! Unexpected data errors! The
failing blocks are now marked as bad!
2020-03-05 09:33:14,665 [OUTERR] Use 'snapraid status' to list the bad
blocks.
2020-03-05 09:33:14,666 [OUTERR] Use 'snapraid -e fix' to recover.
```
