### ISSUE TITLE
min or max for max_log_size

### ISSUE THREAD

**Issue by michael-raps** [Chronial/snapraid-runner#32]
in setup_logger() where the max_log_size is computed, should it not rather be max(config["logging"]["maxsize"],0) * 1024 instead of min(...,0) as we want to have the bigger number and not always "0"?

**Comment by ptoulouse** [comment]
I have an issue where the log file grew out of control and traced it back to this line of code. The max statement always returns 0. Then max_log_size=0 is passed to the logger. For the logging function, 0 means do not rotate log files.

**Comment by michael-raps** [comment]
@ptoulouse that is exactly the problem. At the time of this writing https://github.com/Chronial/snapraid-runner/blob/76af6f739d48638f2f27850b854c48e983fa6d61/snapraid-runner.py#L183 shows the "min" function and not the "max"
In Python the "min()" function returns the smallest value of the provided list of values, which in this case here, will be always 0, no matter what the "config["logging"]["maxsize"]" tells. And with this we don´t get any rotation on the log files.
So it should really be "max(config["logging"]["maxsize"],0)"!

Maybee the owner can have a look? @Chronial ?
