### ISSUE TITLE
Syntax Error snapraid-runner.py

### ISSUE THREAD

**Issue by zoompig** [Chronial/snapraid-runner#37]
I'm getting the following  syntax error when running the script:

  File "/opt/snapraid-runner/snapraid-runner.py", line 42
    def snapraid_command(command, args={}, *,  allow_statuscodes=[]):

I'm not programmer by a long shot, but I'll be happy to provide any info.  I have not altered the python file in any way.
Thanks

**Comment by fmoledina** [comment]
Are you running Python 3?

**Comment by zoompig** [comment]
Yes, I have python3 installed.

**Comment by fmoledina** [comment]
Can you include the exact command you're running the script with?

**Comment by zoompig** [comment]
figured it out,
python2 /opt/snapraid-runner/snapraid-runner.py -c /opt/snapraid-runner/snapraid-runner.conf
Was running in with python2 command from tutorial.  Thanks for your help, you got me going in the right direction.

**Comment by fmoledina** [comment]
Good to hear! You're welcome!
