### ISSUE TITLE
suggestions for scrub

### ISSUE THREAD

**Issue by dpantel** [Chronial/snapraid-runner#44]
You seem to be passing a `--percentage` option to Snapraid for scrub.  Oddly enough, It seems to actually be working, even though that option is not documented.  I think to be sure the script keeps working as intended, the option should be switched to `--plan [percent #]`.

Also, consider running scrub with the `--quiet` option, otherwise the output log is huge since there are 100 lines of scrub output like this: "[OUTPUT] 81%, 350886 MB, 127 MB/s, 487 block/s, CPU 16%, 0:06 ETA"

**Comment by Chronial** [comment]
Thanks for the report. The percentage option is simply the [old version of `--plan`](https://github.com/amadvance/snapraid/blob/77f7bd4cc9755839f1c33496d5a918347851d338/HISTORY#L213-L220).

The spammy output was introduced with the python3 migration. I guess the handling of the `\r` at the end of the progress lines changed.

PRs to fix these issues are welcome.

**Comment by Chronial** [comment]
The --plan argument was added in 4cb7e695afbe0ed6fe66877863955c66fc726477, the progress output was fixed in 8acd9315dd0827cd48415d80302900f42c0af667.
