### ISSUE TITLE
Adding timestamp in log file name

### ISSUE THREAD

**Issue by arobass** [Chronial/snapraid-runner#5]
How to add timestamp in log file "2015-04-27_Snapraid.log"

1- add this line in # Global variables in snapraid-runner.py
dateTimeStamp = time.strftime('%Y-%m-%d') #in the format YYYY-MM-DD

2-  add a file path in the config file : 
[logging]
; log path to write to
filepath = C:\snapraid\logs\
; logfile name to write to, leave empty to disable
file = _Snapraid-runner.log 
; maximum logfile size in KiB, leave empty for infinite
maxsize = 5000

3- change this section : 
if config["logging"]["file"]:
        max_log_size = min(config["logging"]["maxsize"], 0) \* 1024
        file_logger = logging.handlers.RotatingFileHandler(
            config["logging"]["filepath"] + dateTimeStamp + config["logging"]["file"],
            maxBytes=max_log_size,
            backupCount=9)
        file_logger.setFormatter(log_format)
        root_logger.addHandler(file_logger)

**Comment by michael-raps** [comment]
The proposed solution here would render the max file count (backupCount=9) of the RotatingFileHandler ineffective as with every run the filename will change. You should then take care to remove old log files "by hand" before your disk runs out of space.

**Comment by Chronial** [comment]
You might be looking for [TimedRotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler)
