### ISSUE TITLE
scrub plan vs. percentage

### ISSUE THREAD

**Issue by kevindd992002** [Chronial/snapraid-runner#52]
@Chronial 

So the support for the "plan" switch for scrub is still under ["Unreleased" in the changelogs](https://github.com/Chronial/snapraid-runner#unreleased). But plan is already in your [snapraid-runner.conf.example](https://github.com/Chronial/snapraid-runner/blob/master/snapraid-runner.conf.example) file. Does that mean that this plan parameter will still work with the current release of your py script (0.5)?

**Comment by Chronial** [comment]
The state on master (and the conf file you linked) represent the unreleased state. The [conf file of the 0.5 release](https://github.com/Chronial/snapraid-runner/blob/v0.5/snapraid-runner.conf.example) (note the 0.5 in that url) does not contain the plan setting.

But there is no good reason to not just use the script from master, which supports the plan setting.

**Comment by kevindd992002** [comment]
I see. Yes, I'm using the script from the master branch. Thanks for clarifying.
