### ISSUE TITLE
Newbie with email issue

### ISSUE THREAD

**Issue by Fumby01** [Chronial/snapraid-runner#60]
Hi Christian, I am not sure how to ask you for help in github so hopefully this message is ok.

I am a newbie to Python. I have managed to get your script working and it is great. The only thing I can't get working is the email. What parts of the script needs to be updated with my address, server, PW etc?

I would really appreciate if you can point me in the right direction.

**Comment by Fumby01** [comment]
This is what I get after everything has completed succesfully:

2023-02-02 08:47:13,758 [INFO  ] All done
2023-02-02 08:47:14,214 [ERROR ] Failed to send email
Traceback (most recent call last):
  File "C:\SnapRaid\snapraid-runner.py", line 129, in finish
    send_email(is_success)
  File "C:\SnapRaid\snapraid-runner.py", line 118, in send_email
    server.login(config["smtp"]["user"], config["smtp"]["password"])
  File "C:\Users\c_caw\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 716, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2023-02-02 08:47:14,225 [INFO  ] Run finished successfully

**Comment by Chronial** [comment]
You should not change anything in the script – if you did that, please download the original version again. Only change the `snapraid-runner.conf`.

What email provider are you using? I assume you need to change the setting for `ssl` or `tsl` to match what your email provider supports.

**Comment by Fumby01** [comment]
Hi Christian, thanks very much. I have a hotmail account. I dont think i made changes to the python script but i will redownload and have another look at the conf file.

Hopefully i will get it going.

Thanks very much for the reply.

Cheers.

Kind Regards,

Chris Cawthorn
________________________________

**Comment by Fumby01** [comment]
Hi Christian, thanks for your great script and your help.

You were spot on. SSL set to false was the only issue.
