### ISSUE TITLE
Issue with gmail smtp workaround?

### ISSUE THREAD

**Issue by treverehrfurth** [Chronial/snapraid-runner#61]
Hello all, this might be a noob question but ever since gmail removed their less secure app access, I haven't been able to get any success or failure emails to send.

Is there a way to add in the app key that google has you generate to get these success/error emails to send?

Please help, thank you!

**Comment by ljo123** [comment]
You need to go into your google account then Security -> App Passwords and create a new password. Then in snapraid-runner.conf you put:

```
[smtp]
host = smtp.gmail.com
; leave empty for default port
port = 587
; set to "true" to activate
ssl = false
tls = true
user = myemail@gmail.com
password = <app password>
```

**Comment by treverehrfurth** [comment]
@ljo123 awesome, that did the trick. Thank you!

**Comment by Chronial** [comment]
@ljo123 Thanks a lot for that explanation, I added it to the project's wiki so it's easier to find: https://github.com/Chronial/snapraid-runner/wiki/How-to-use-snapraid-runner-with-gmail
